// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXCUM2AxKD73rQIy53ArxDspVYbVDBJ68',
    appId: '1:233388384349:web:089c4df4fd9230c9076db4',
    messagingSenderId: '233388384349',
    projectId: 'curling-scoreboard-dev',
    authDomain: 'curling-scoreboard-dev.firebaseapp.com',
    storageBucket: 'curling-scoreboard-dev.firebasestorage.app',
    measurementId: 'G-GJD7QRHKDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOfdeNZrDngUNiZowXO8G1--2dRZAJwhg',
    appId: '1:233388384349:android:49cb58e9fc227bb4076db4',
    messagingSenderId: '233388384349',
    projectId: 'curling-scoreboard-dev',
    storageBucket: 'curling-scoreboard-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_4Cp391YgiusOinT81J2QDYku-sfisQ4',
    appId: '1:233388384349:ios:8eb699f4d6f3feba076db4',
    messagingSenderId: '233388384349',
    projectId: 'curling-scoreboard-dev',
    storageBucket: 'curling-scoreboard-dev.firebasestorage.app',
    iosBundleId: 'com.cloudgatestudios.curlingScoreboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_4Cp391YgiusOinT81J2QDYku-sfisQ4',
    appId: '1:233388384349:ios:8eb699f4d6f3feba076db4',
    messagingSenderId: '233388384349',
    projectId: 'curling-scoreboard-dev',
    storageBucket: 'curling-scoreboard-dev.firebasestorage.app',
    iosBundleId: 'com.cloudgatestudios.curlingScoreboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr7plQ3znWRAAVyph84NUcFUiScgm_HaQ',
    appId: '1:233388384349:web:b5bf8ecbc17717ae076db4',
    messagingSenderId: '233388384349',
    projectId: 'curling-scoreboard-dev',
    authDomain: 'curling-scoreboard-dev.firebaseapp.com',
    storageBucket: 'curling-scoreboard-dev.firebasestorage.app',
    measurementId: 'G-9YWJ5B9HYD',
  );
}
