// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKWdlQbyMrhlVd7IvzXlFGukUHeGgHZh4',
    appId: '1:513864345938:web:38ea0259c2b9099002b28b',
    messagingSenderId: '513864345938',
    projectId: 'curling-scoreboard-prod',
    authDomain: 'curling-scoreboard-prod.firebaseapp.com',
    storageBucket: 'curling-scoreboard-prod.firebasestorage.app',
    measurementId: 'G-62KV6P67L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0MxOmq0NOJMtnkaG4r-zIR18-OkHGXI',
    appId: '1:513864345938:android:025e8bf3a1108da002b28b',
    messagingSenderId: '513864345938',
    projectId: 'curling-scoreboard-prod',
    storageBucket: 'curling-scoreboard-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1HdcD3gjOSk3Zk_6mQUs72Dh5e4PNZ0Q',
    appId: '1:513864345938:ios:0e201970287f903f02b28b',
    messagingSenderId: '513864345938',
    projectId: 'curling-scoreboard-prod',
    storageBucket: 'curling-scoreboard-prod.firebasestorage.app',
    iosBundleId: 'com.cloudgatestudios.curlingScoreboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1HdcD3gjOSk3Zk_6mQUs72Dh5e4PNZ0Q',
    appId: '1:513864345938:ios:0e201970287f903f02b28b',
    messagingSenderId: '513864345938',
    projectId: 'curling-scoreboard-prod',
    storageBucket: 'curling-scoreboard-prod.firebasestorage.app',
    iosBundleId: 'com.cloudgatestudios.curlingScoreboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKWdlQbyMrhlVd7IvzXlFGukUHeGgHZh4',
    appId: '1:513864345938:web:8bb718b3e5cc0ab702b28b',
    messagingSenderId: '513864345938',
    projectId: 'curling-scoreboard-prod',
    authDomain: 'curling-scoreboard-prod.firebaseapp.com',
    storageBucket: 'curling-scoreboard-prod.firebasestorage.app',
    measurementId: 'G-P2BTJJVHKL',
  );
}
