version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/app"
    schedule:
      interval: "weekly"
    groups:
      app:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
    groups:
      functions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/admin"
    schedule:
      interval: "weekly"
    groups:
      admin:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    groups:
      scripts:
        patterns:
          - "*"
