name: Deploy App - Web - Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Tag to Deploy
        required: true

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy App - Web - Prod
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.version }}
      - uses: subosito/flutter-action@v2.23.0
        with:
          flutter-version: "3.44.0"
          channel: "stable"
      - run: flutter packages get
      - run: flutter build web -t lib/main.dart --dart-define=FIREBASE_ENV=prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CURLING_SCOREBOARD_PROD }}"
          projectId: curling-scoreboard-prod
          expires: 30d
          channelId: live
          entryPoint: .
          target: app
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CURLING_SCOREBOARD_PROD }}"
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"
      - name: Install Function Dependencies
        run: cd functions && npm ci
      - name: Build Functions
        run: cd functions && npm run build
      - name: Deploy Firestore and Functions
        run: npx firebase-tools@latest deploy --only firestore,functions --force --project curling-scoreboard-prod
        working-directory: ${{ github.workspace }}
