name: Deploy Admin Portal - Dev

on:
  push:
    branches:
      - main

jobs:
  deploy-admin-dev:
    runs-on: ubuntu-latest
    name: Deploy Admin Portal - Dev
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install admin portal dependencies
        working-directory: ./admin
        run: npm ci

      - name: Build admin portal
        working-directory: ./admin
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CURLING_SCOREBOARD_DEV }}"
          projectId: curling-scoreboard-dev
          channelId: live
          target: admin
          entryPoint: .
