name: Deploy Admin Portal - Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Tag to Deploy
        required: true

jobs:
  deploy-admin-prod:
    runs-on: ubuntu-latest
    name: Deploy Admin Portal - Prod
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.version }}

      - uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install admin portal dependencies
        working-directory: ./admin
        run: npm ci

      - name: Build admin portal
        working-directory: ./admin
        env:
          VITE_ENV: prod
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CURLING_SCOREBOARD_PROD }}'
          projectId: curling-scoreboard-prod
          channelId: live
          target: admin
          entryPoint: .
